create table COURSE(
 ID INT PRIMARY KEY,
 COURSE_NAME VARCHAR(40)
);

CREATE TABLE STUDENT(
  ID INT PRIMARY KEY,
  FIRST_NAME VARCHAR(20),
  LAST_NAME VARCHAR(20),
  COURSE_ID INT,
  FOREIGN key(COURSE_ID) REFERENCES COURSE(ID)
 );